routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('icons', 'IconController@index');

Auth::routes(['verify' => true]);

Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories','CategoryController');
    Route::resource('countries','CountryController');
    Route::resource('users','UserController');
    Route::resource('agencies','AgencyController');
    Route::resource('companies','CompanyController');
    Route::resource('enquiries','EnquiryController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('challenges','ChallengeController');
    
    Route::get('profile/{user}/enquiries','ProfileController@enquiries')->name('profile.enquiries');
    Route::get('profile/{user}','ProfileController@show')->name('profile.show');
    Route::get('profile/{user}/visit','ProfileController@visit')->name('profile.visit');
    Route::get('profile/{user}/learn','ProfileController@learn')->name('profile.learn');
    Route::get('profile/{user}/experience','ProfileController@experience')->name('profile.experience');

    
    Route::get('destinations','DestinationController@index')->name('destinations.index');
    
    Route::post('destinations','DestinationController@store')->name('destinations.store');
    Route::delete('destinations/{country}','DestinationController@destroy')->name('destinations.destroy');
    //Route::post('destinations','DestinationController@bucketlist')->name('destinations.bucketlist');
    
    Route::get('visits', function(){
        return 'hola';
    })->name('visits');
    
    Route::get('trashed-agencies','CompanyController@trashed')->name('trashed_agencies.trashed');
    Route::get('trashed-agencies/{agency}','CompanyController@show_trashed')->name('trashed_agencies.show_trashed');
    Route::put('restore-agency/{agency}','CompanyController@restore')->name('restored_agency');    
});

app/Http/Controllers/DestinationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Country;
use App\User;
use JavaScript;

class DestinationController extends Controller
{
    public function index()
    {
        // JavaScript::put([
        //         'gabo' => 'Gabriel es el mejor'
        // ]);
        
        $visitedCountries = Country::all();

        //dd(visitedCountries);

        return view('destinations.index')
            ->with('countryList', Country::all())
            ->with('user', auth()->user());
    }

    public function store(Request $request)
    {
        //dd($request->all());

        $search = $request->country;
        $user = User::find(auth()->user()->id);

        $country = Country::where('name', 'LIKE', "%{$search}%")->first();

        $countries = $user->visitedCountries;

        if ( $countries->contains('id', $country->id) ) {
            session()->flash('error', 'The country you selected is already in the list');
        } else{
            if ($request->status == 'visited') {
                $user->visitedCountries()->attach($country->id, ['status' => $request->status]);
            } else {
                $user->bucketListCountries()->attach($country->id, ['status' => $request->status]);
            }
            session()->flash('success', 'Country added to the list successfully');
        }
        //dd($countries->toArray());        
        //dd($countries->contains('id', $country->id));
        //pluck('countries')->toArray()

        return redirect()->back();
    }

    public function destroy($id, Request $request)
    {
        $user = $user = User::find(auth()->user()->id);
        if ($request->status == 'bucketlist') {
            $user->bucketListCountries()->detach($id);
        } else {
            $user->visitedCountries()->detach($id);
        }

        session()->flash('success', 'Country removed from list successfully');
        return redirect()->back();
    }
}

resources/views/destinations/index.blade.php
@extends('layouts.app')

@section('head')
<link rel="stylesheet" type="text/css" href="//github.com/downloads/lafeber/world-flags-sprite/flags16.css" />
@endsection

@section('content')
<header class="pt-8 pb-4 flex flex-wrap justify-between items-center">
    <div class="w-full md:w-1/3 mx-3 mb-2">
        <h2 class="text-2xl font-bold leading-7 sm:text-3xl sm:leading-9 sm:truncate text-gray-800">
            My destinations
        </h2>
    </div>
    <div class="w-full md:w-1/3 text-right mx-3">
        <a href="{{ route('enquiries.create') }}"
            class="bg-red-600 text-white rounded py-2 px-3 hover:bg-indigo-700 hover:text-white w-full md:w-auto text-center">
            Request a travel offer
        </a>
    </div>
</header>

<div class="flex flex-wrap -px-3">
    <div class="w-full md:w-3/4 mb-5 md:mb-0 px-3">
        <div id="regions_div" class="w-full h-full rounded-lg overflow-hidden"></div>
    </div>
    <div class="w-full md:w-1/4 px-3 flex flex-col justify-between -my-1">

        <div class="border rounded-lg text-center py-3 my-1 hover:shadow bg-white">
            <span class="text-6xl block font-bold text-gray-700">{{ $countryList->count() }}</span>
            <span class="uppercase text-gray-600">Total countries</span>
        </div>

        <div class="border rounded-lg text-center py-3 my-1 hover:shadow bg-white">
            <span
                class="text-6xl block font-bold text-green-500 mb-0 pb-0">{{ $user->visitedCountries->count() }}</span>
            <span class="uppercase text-gray-600">visited countries</span>
        </div>

        <div class="border rounded-lg text-center py-3 my-1 hover:shadow bg-white">
            <span class="text-6xl block text-red-600 font-bold">{{ $user->bucketListCountries->count() }} </span>
            <span class="uppercase text-gray-600">Countries to visit</span>
        </div>
        {{-- <div id="gauge" class="w-full"></div> --}}
    </div>
</div>

<br>
<br>

<section class="flex flex-wrap -px-2">
    <div class="w-full md:w-1/2 px-2">
        <div x-data="{ open: false }">
            <div class="flex justify-between items-end">
                <h2 class="text-lg font-bold text-gray-800">Visited Countries</h2>
                <button
                    class="inline-flex items-center mt-4 bg-gray-300 py-1 px-2 rounded text-gray-800 hover:bg-pink-700 hover:text-white focus:outline-none"
                    @click="open = true" onclick="focusMethod()" x-show="!open">
                    <input type="hidden" name="status" value="value">
                    @include('icons.add') <span class="pl-2">Add</span>
                </button>
            </div>
            <div x-show="open" @click.away="open = false" class="mt-4">
                @include('shared.country_input', ['status'=> 'visited', 'label'=>'Add country and press enter'])
            </div>
        </div>
        @livewire('country-list', ['list'=> 'visitedCountries'])
    </div>

    <div class="w-full md:w-1/2 px-2">
        <div x-data="{ open: false }">
            <div class="flex justify-between items-end">
                <h2 class="text-lg font-bold text-gray-800">Bucketlist</h2>
                <button
                    class="inline-flex items-center mt-4 bg-gray-300 py-1 px-2 rounded-full text-gray-800 hover:bg-indigo-700 hover:text-white focus:outline-none"
                    @click="open = true" onclick="focusMethod()" x-show="!open">
                    @include('icons.add') <span class="pl-2">Add</span>
                </button>
            </div>

            <div x-show="open" @click.away="open = false" class="mt-4">
                @include('shared.country_input', ['status'=> 'bucketlist', 'label'=>'Add country this'])
            </div>
        </div>
        @livewire('country-list', ['list'=> 'bucketlistCountries'])
    </div>
</section>

@endsection


@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/places.js@1.18.1"></script>
<script>
    console.log('name:' + gabo);
</script>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    let visited = <?= json_encode($user->visitedCountries->toArray()); ?>;
    let bucketlist = <?= json_encode($user->bucketListCountries->toArray()); ?>;
    
    google.charts.load('current', {
        'packages': ['geochart'],
        // Note: you will need to get a mapsApiKey for your project.
        // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
        'mapsApiKey': 'AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY'
    });

    google.charts.setOnLoadCallback(drawRegionsMap);

    function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([]);
        data.addColumn('string', 'Country');
        data.addColumn('number', 'Want to go');
        visited.forEach(element => { 
            data.addRow([element.alpha_2_Code,100]); 
        });
        
        bucketlist.forEach(element => { 
            data.addRow([element.alpha_2_Code, 0]); 
        });
        

        var options = {
            //region: '002', // Africa
            colorAxis: {colors: ['#84dcc6', '#ff595e']},
            defaultColor: '#ff595e',
            backgroundColor: '#a9def9',
            legend: 'none'
        };

    var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

    chart.draw(data, options);
    }

    
    google.charts.load('current', {'packages':['gauge']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Visited', visited.length],
          ['Bucketlist', bucketlist.length],          
        ]);

        var options = {
          width: 350, height: 500,
          redFrom: 200, redTo: 250,
          yellowFrom: 180, yellowTo: 200,
          minorTicks: 5,
          max: 250,
        };

        var chart = new google.visualization.Gauge(document.getElementById('gauge'));

        chart.draw(data, options);
    }
</script>
@endsection